import js from '@eslint/js';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import feng3dPlugin from 'eslint-plugin-feng3d';

export default [
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'lib/**',
      'public/**',
      '*.config.js',
      'packages/webgpu/examples/**',
      'examples/**',
      // packages/editor：编辑器刚从独立仓库迁入，与主仓 API 存在约 1100 处不兼容
      // （主仓移除了 filesystem/assets 子系统等）。正在做 API 适配，
      // 适配完成后应移除本条忽略，让编辑器代码纳入统一 lint（含响应式纪律规则）。
      'packages/editor/**',
    ],
  },
  js.configs.recommended,
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FormData: 'readonly',
        Headers: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        HTMLElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLAnchorElement: 'readonly',
        HTMLIFrameElement: 'readonly',
        HTMLTemplateElement: 'readonly',
        OffscreenCanvas: 'readonly',
        ImageData: 'readonly',
        ImageBitmap: 'readonly',
        createImageBitmap: 'readonly',
        devicePixelRatio: 'readonly',
        getComputedStyle: 'readonly',
        ResizeObserver: 'readonly',
        ResizeObserverEntry: 'readonly',
        MouseEvent: 'readonly',
        // WebGPU globals
        GPUBuffer: 'readonly',
        GPUBindGroup: 'readonly',
        GPUCompareFunction: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
      'feng3d': feng3dPlugin,
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      'semi': ['error', 'always'],
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-function-type': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-unsafe-declaration-merging': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      '@typescript-eslint/no-this-alias': 'off',
      '@typescript-eslint/prefer-as-const': 'off',
      '@typescript-eslint/no-duplicate-enum-values': 'off',
      '@typescript-eslint/triple-slash-reference': 'off',
      '@typescript-eslint/no-namespace': 'off',
      'no-prototype-builtins': 'off',
      'no-undef': 'off',
      'no-redeclare': 'off',
      'no-constant-binary-expression': 'off',
      'preserve-caught-error': 'off',
      'no-useless-assignment': 'off',
      'no-case-declarations': 'off',
      'no-useless-escape': 'off',
      'no-unassigned-vars': 'off',
      // Feng3D 响应式对象规则（源码文件）
      'feng3d/reactive-naming': 'error',
      'feng3d/no-reactive-export': 'error',
      'feng3d/no-reactive-argument': 'error',
      'feng3d/effect-annotation': 'error',
    },
  },
  // 测试文件规则（降级为警告）
  {
    files: ['**/*.spec.ts', '**/test/**/*.ts'],
    ...js.configs.recommended,
    plugins: {
      '@typescript-eslint': tsPlugin,
      'feng3d': feng3dPlugin,
    },
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FormData: 'readonly',
        Headers: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        HTMLElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLAnchorElement: 'readonly',
        HTMLIFrameElement: 'readonly',
        HTMLTemplateElement: 'readonly',
        OffscreenCanvas: 'readonly',
        ImageData: 'readonly',
        ImageBitmap: 'readonly',
        createImageBitmap: 'readonly',
        devicePixelRatio: 'readonly',
        getComputedStyle: 'readonly',
        ResizeObserver: 'readonly',
        ResizeObserverEntry: 'readonly',
        MouseEvent: 'readonly',
        GPUBuffer: 'readonly',
        GPUBindGroup: 'readonly',
        GPUCompareFunction: 'readonly',
      },
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      'semi': ['error', 'always'],
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-function-type': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-unsafe-declaration-merging': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      '@typescript-eslint/no-this-alias': 'off',
      'no-prototype-builtins': 'off',
      'no-undef': 'off',
      'no-redeclare': 'off',
      'no-constant-binary-expression': 'off',
      'preserve-caught-error': 'off',
      // Feng3D 响应式对象规则（测试文件仅警告）
      'feng3d/reactive-naming': 'off',
      'feng3d/no-reactive-export': 'off',
      'feng3d/no-reactive-argument': 'off',
      'feng3d/effect-annotation': 'off',
    },
  },
];
