export default {
    "base": [
        "Container3DTest",
        "FPSControllerTest",
        "BillboardTest",
        "MousePickTest",
        "SkyBoxTest",
        "FogTest",
        "ScriptTest",
        "ThreejsCubeTest",
        "ThreejsGeometriesTest",
        "ThreejsInteractiveCubesTest",
    ],
    "material": [
        "PointMaterialTest",
        "SegmentMaterialTest",
        "StandardMaterialTest",
        "TextureMaterialTest",
    ],
    "geometry": [
        "PrimitiveTest",
    ],
    "lights": [
        "PointLightTest",
    ],
    "advanced": [
        "TerrainTest",
    ],
    "away3d": [
        "Basic_View",
        "Basic_SkyBox",
        "Basic_Shading",
        "DebugShadowMap",
    ],
    "font": [
        "GeometryFontTest"
    ],
    "webgl": [
        "webgl_geometry_colors",
        "webgl_buffergeometry_lines",
        "webgl_buffergeometry_points",
        "webgl_materials_texture_filters",
        "webgl_geometry_terrain",
        "webgl_lights_spotlight",
        "webgl_interactive_voxelpainter",
        "webgl_geometry_convex",
        "webgl_camera",
        "webgl_buffergeometry_indexed",
        "webgl_lines_colors",
        "webgl_shadowmesh",
        "webgl_buffergeometry_points_interleaved",
        "webgl_buffergeometry_lines_indexed",
        "webgl_buffergeometry",
        "webgl_buffergeometry_uint",
        "webgl_lines_dashed",
        "webgl_interactive_buffergeometry",
        "webgl_materials_blending",
        "webgl_shadowmap",
        "webgl_geometry_extrude_splines",
        "webgl_lights_hemisphere",
        "webgl_lights_physical",
        "webgl_materials_cubemap",
        "webgl_materials_cubemap_refraction",
        "webgl_geometry_teapot",
        "webgl_geometry_shapes",
        "webgl_materials_normal",
        "webgl_geometry_extrude_shapes",
        "webgl_buffergeometry_instancing",
        "webgl_interactive_cubes_ortho",
        "webgl_geometry_browser",
        "webgl_loader_stl",
        "webgl_loader_ply",
        "webgl_loader_obj",
        "webgl_loader_gltf",
        "webgl_geometry_cube",
        "webgl_buffergeometry_drawrange",
        "webgl_materials_texture_canvas",
        "webgl_geometries",
        "webgl_materials_envmaps",
        "webgl_materials_texture_anisotropy",
        "webgl_geometry_terrain_raycast",
        "webgl_buffergeometry_selective_draw",
    ],
} as const;
