import { WebGPU } from '@feng3d/webgpu';
import { logic, Object3D, reactive, Scene, StandardMaterial, View, ticker } from 'feng3d';
import '@feng3d/addons';
const wc = document.getElementById('webgpu') as HTMLCanvasElement;
const webgpu = await new WebGPU().init();
const polys: Object3D[] = [];
const types = ['TetrahedronGeometry', 'OctahedronGeometry', 'IcosahedronGeometry', 'CubeGeometry', 'DodecahedronGeometry'];
const colors: [number,number,number][] = [[1,0.3,0.3],[0.3,1,0.3],[0.3,0.3,1],[1,1,0.3],[1,0.3,1]];
for (let i = 0; i < 5; i++) polys.push({ __type__: 'Object3D', name: `p${i}`, position: { x: (i-2)*3, y: 0, z: 0 }, rotation: { x: 0, y: 0, z: 0 }, components: [{ __type__: 'MeshRenderer', geometry: { __type__: types[i], radius: 1.2, detail: 0 } as never, material: { __type__: 'StandardMaterial', uniforms: { u_diffuse: { __type__: 'Color4', r: colors[i][0], g: colors[i][1], b: colors[i][2], a: 1 }, u_specular: { __type__: 'Color4', r: 0.3, g: 0.3, b: 0.3, a: 1 }, u_glossiness: 30, u_reflectivity: 0 } } }] });
const v: View = { __type__: 'View', canvas: wc, root: { __type__: 'Object3D', name: 'U', components: [{ __type__: 'Scene', background: { __type__: 'Color4', r: 0.1, g: 0.1, b: 0.1, a: 1 }, ambientColor: { __type__: 'Color4', r: 0.5, g: 0.5, b: 0.5, a: 1 } }], children: [{ __type__: 'Object3D', name: 'cam', position: { x: 0, y: 2, z: 10 }, rotation: { x: 0, y: 0, z: 0 }, components: [{ __type__: 'PerspectiveCamera', fov: 50, aspect: wc.width/wc.height, near: 0.1, far: 100 }, { __type__: 'OrbitControls', target: { x: 0, y: 0, z: 0 } }] }, { __type__: 'Object3D', name: 'l', position: { x: 1, y: 1, z: 1 }, components: [{ __type__: 'DirectionalLight', color: { __type__: 'Color3', r: 1, g: 1, b: 1 }, intensity: 1 }] }, ...polys] } };
const vl = logic(v);
ticker.onframe(() => { for (const p of polys) reactive(p.rotation as {y:number}).y += 0.005; webgpu.submit(vl.submit); });
