import { WebGPU } from '@feng3d/webgpu';
import { logic, Object3D, PointGeometry, PointMaterial, reactive, Scene, View, ticker } from 'feng3d';
const wc = document.getElementById('webgpu') as HTMLCanvasElement;
const webgpu = await new WebGPU().init();
const N = 4000; const pts: PointGeometry['points'] = []; const base: { x: number; ph: number }[] = [];
for (let i = 0; i < N; i++) { base.push({ x: (Math.random() - 0.5) * 400, ph: Math.random() * 6.28 }); pts.push({ position: { x: 0, y: 0, z: 0 }, color: { __type__: 'Color4', r: 0.2, g: 0.8, b: 0.5, a: 0.6 } }); }
const v: View = { __type__: 'View', canvas: wc, root: { __type__: 'Object3D', name: 'U', components: [{ __type__: 'Scene', background: { __type__: 'Color4', r: 0.01, g: 0.02, b: 0.05, a: 1 } }], children: [{ __type__: 'Object3D', name: 'cam', position: { x: 0, y: 0, z: 500 }, rotation: { x: 0, y: 0, z: 0 }, components: [{ __type__: 'PerspectiveCamera', fov: 60, aspect: wc.width / wc.height, near: 1, far: 2000 }, { __type__: 'OrbitControls', target: { x: 0, y: 0, z: 0 } }] }, { __type__: 'Object3D', name: 'aurora', components: [{ __type__: 'MeshRenderer', geometry: { __type__: 'PointGeometry', points: pts } as PointGeometry, material: { __type__: 'PointMaterial', uniforms: { u_color: { __type__: 'Color4', r: 1, g: 1, b: 1, a: 1 }, u_PointSize: 5 } } as PointMaterial }] }] } };
const vl = logic(v);
ticker.onframe(() => { const t = Date.now() * 0.001; for (let i = 0; i < N; i++) { const b = base[i]; const y = Math.sin(b.x * 0.01 + t + b.ph) * 100; reactive(pts[i]).position = { x: b.x, y, z: Math.cos(b.x * 0.008 + t * 0.7 + b.ph) * 80 }; reactive(pts[i]).color = { __type__: 'Color4', r: 0.1 + Math.sin(t + b.ph) * 0.2, g: 0.6 + Math.sin(t + b.ph + 1) * 0.3, b: 0.4 + Math.sin(t + b.ph + 3) * 0.3, a: 0.6 }; } webgpu.submit(vl.submit); });
