import { WebGPU } from '@feng3d/webgpu';
import { logic, Object3D, PointGeometry, PointMaterial, reactive, Scene, View, ticker } from 'feng3d';
const wc = document.getElementById('webgpu') as HTMLCanvasElement;
const webgpu = await new WebGPU().init();
const N = 6000; const pts: PointGeometry['points'] = []; const base: {r:number;a:number;ph:number;sp:number}[] = [];
for (let i = 0; i < N; i++) { const r = Math.pow(Math.random(), 0.5) * 200; const a = Math.random() * 6.28; const ph = Math.acos(Math.random() * 2 - 1); const sp = 0.001 + Math.random() * 0.003; base.push({ r, a, ph, sp }); pts.push({ position: { x: r * Math.sin(ph) * Math.cos(a), y: r * Math.cos(ph), z: r * Math.sin(ph) * Math.sin(a) }, color: { __type__: 'Color4', r: r / 200 * 0.8 + 0.2, g: 0.3, b: 1 - r / 200 * 0.5, a: 0.7 } }); }
let gr: { x: number; y: number; z: number };
const v: View = { __type__: 'View', canvas: wc, root: { __type__: 'Object3D', name: 'U', components: [{ __type__: 'Scene', background: { __type__: 'Color4', r: 0.01, g: 0.01, b: 0.03, a: 1 } }], children: [{ __type__: 'Object3D', name: 'cam', position: { x: 0, y: 0, z: 400 }, rotation: gr = { x: 0, y: 0, z: 0 }, components: [{ __type__: 'PerspectiveCamera', fov: 60, aspect: wc.width / wc.height, near: 1, far: 2000 }, { __type__: 'OrbitControls', target: { x: 0, y: 0, z: 0 }, autoRotate: true, autoRotateSpeed: 0.3 }] }, { __type__: 'Object3D', name: 'nebula', components: [{ __type__: 'MeshRenderer', geometry: { __type__: 'PointGeometry', points: pts } as PointGeometry, material: { __type__: 'PointMaterial', uniforms: { u_color: { __type__: 'Color4', r: 1, g: 1, b: 1, a: 1 }, u_PointSize: 4 } } as PointMaterial }] }] } };
const vl = logic(v);
ticker.onframe(() => { const t = Date.now() * 0.001; for (let i = 0; i < N; i++) { const b = base[i]; const a = b.a + t * b.sp; reactive(pts[i]).position = { x: b.r * Math.sin(b.ph) * Math.cos(a), y: b.r * Math.cos(b.ph), z: b.r * Math.sin(b.ph) * Math.sin(a) }; } webgpu.submit(vl.submit); });
