import { WebGPU } from '@feng3d/webgpu';
import { logic, Object3D, reactive, Scene, StandardMaterial, View, ticker } from 'feng3d';
const wc = document.getElementById('webgpu') as HTMLCanvasElement;
const webgpu = await new WebGPU().init();
const boxes: Object3D[] = [];
for (let i = 0; i < 30; i++) boxes.push({ __type__: 'Object3D', name: `b${i}`, position: { x: (i%6-2.5)*4, y: 0, z: Math.floor(i/6)*-8-5 }, rotation: { x: 0, y: 0, z: 0 }, components: [{ __type__: 'MeshRenderer', geometry: { __type__: 'CubeGeometry', width: 2, height: 2, depth: 2 }, material: { __type__: 'StandardMaterial', uniforms: { u_diffuse: { __type__: 'Color4', r: 1-i/30*0.8, g: 0.5, b: 0.3, a: 1 }, u_specular: { __type__: 'Color4', r: 0, g: 0, b: 0, a: 1 }, u_glossiness: 0, u_reflectivity: 0 } } }] });
let r: {x:number;y:number;z:number};
const v: View = { __type__: 'View', canvas: wc, root: { __type__: 'Object3D', name: 'Untitled', components: [{ __type__: 'Scene', background: { __type__: 'Color4', r: 0.5, g: 0.6, b: 0.7, a: 1 }, ambientColor: { __type__: 'Color4', r: 0.5, g: 0.5, b: 0.5, a: 1 } }], children: [{ __type__: 'Object3D', name: 'cam', position: { x: 0, y: 5, z: 15 }, rotation: r={x:0,y:0,z:0}, components: [{ __type__: 'PerspectiveCamera', fov: 60, aspect: wc.width/wc.height, near: 0.1, far: 100 }, { __type__: 'OrbitControls', target: { x: 0, y: 0, z: -15 } }] }, { __type__: 'Object3D', name: 'l', position: { x: 1, y: 1, z: 1 }, components: [{ __type__: 'DirectionalLight', color: { __type__: 'Color3', r: 1, g: 1, b: 1 }, intensity: 1 }] }, ...boxes] } };
const vl = logic(v);
ticker.onframe(() => { reactive(r).y += 0.002; webgpu.submit(vl.submit); });
