import { WebGPU } from '@feng3d/webgpu';
import { logic, Object3D, PointGeometry, PointMaterial, reactive, Scene, View, ticker } from 'feng3d';
const wc = document.getElementById('webgpu') as HTMLCanvasElement;
const webgpu = await new WebGPU().init();
const N = 500; const pts: PointGeometry['points'] = []; const vel: { x: number; y: number; z: number }[] = []; const life: number[] = [];
for (let i = 0; i < N; i++) { vel.push({ x: 0, y: 0, z: 0 }); life.push(0); pts.push({ position: { x: 9999, y: 0, z: 9999 }, color: { __type__: 'Color4', r: 0.3, g: 0.7, b: 1, a: 0 } }); }
let spawnT = 0;
const v: View = { __type__: 'View', canvas: wc, root: { __type__: 'Object3D', name: 'U', components: [{ __type__: 'Scene', background: { __type__: 'Color4', r: 0.05, g: 0.05, b: 0.08, a: 1 } }], children: [{ __type__: 'Object3D', name: 'cam', position: { x: 30, y: 20, z: 40 }, rotation: { x: 0, y: 0, z: 0 }, components: [{ __type__: 'PerspectiveCamera', fov: 50, aspect: wc.width / wc.height, near: 1, far: 500, frustumCulling: false }, { __type__: 'OrbitControls', target: { x: 0, y: 10, z: 0 } }] }, { __type__: 'Object3D', name: 'fountain', components: [{ __type__: 'MeshRenderer', geometry: { __type__: 'PointGeometry', points: pts } as PointGeometry, material: { __type__: 'PointMaterial', uniforms: { u_color: { __type__: 'Color4', r: 1, g: 1, b: 1, a: 1 }, u_PointSize: 8 } } as PointMaterial }] }] } };
const vl = logic(v);
ticker.onframe(() => { spawnT++; if (spawnT > 2) { spawnT = 0; for (let j = 0; j < 5; j++) { const i = Math.floor(Math.random() * N); const a = Math.random() * 6.28; const sp = Math.random() * 1 + 0.5; vel[i] = { x: Math.cos(a) * sp * 3, y: Math.random() * 3 + 4, z: Math.sin(a) * sp * 3 }; life[i] = 1; reactive(pts[i]).position = { x: 0, y: 0, z: 0 }; reactive(pts[i]).color = { __type__: 'Color4', r: 0.2 + Math.random() * 0.3, g: 0.5 + Math.random() * 0.5, b: 1, a: 1 }; } } for (let i = 0; i < N; i++) { if (life[i] <= 0) continue; vel[i].y -= 0.15; const p = pts[i].position as { x: number; y: number; z: number }; reactive(pts[i]).position = { x: p.x + vel[i].x, y: p.y + vel[i].y, z: p.z + vel[i].z }; life[i] -= 0.01; reactive(pts[i]).color = { __type__: 'Color4', r: pts[i].color.r, g: pts[i].color.g, b: pts[i].color.b, a: Math.max(0, life[i]) }; } webgpu.submit(vl.submit); });
