import { WebGPU } from '@feng3d/webgpu';
import { logic, Object3D, reactive, Scene, StandardMaterial, View, ticker } from 'feng3d';
const wc = document.getElementById('webgpu') as HTMLCanvasElement;
const webgpu = await new WebGPU().init();
const lights: Object3D[] = [];
for (let i = 0; i < 6; i++) { const hue = i / 6; lights.push({ __type__: 'Object3D', name: 'pl' + i, position: { x: 0, y: 0, z: 0 }, components: [{ __type__: 'PointLight', color: { __type__: 'Color3', r: Math.sin(hue * 6.28) * 0.5 + 0.5, g: Math.sin(hue * 6.28 + 2.1) * 0.5 + 0.5, b: Math.sin(hue * 6.28 + 4.2) * 0.5 + 0.5 }, intensity: 3, range: 15 }] }); }
const v: View = { __type__: 'View', canvas: wc, root: { __type__: 'Object3D', name: 'U', components: [{ __type__: 'Scene', background: { __type__: 'Color4', r: 0.01, g: 0.01, b: 0.02, a: 1 }, ambientColor: { __type__: 'Color4', r: 0.05, g: 0.05, b: 0.05, a: 1 } }], children: [{ __type__: 'Object3D', name: 'cam', position: { x: 0, y: 5, z: 15 }, rotation: { x: 0, y: 0, z: 0 }, components: [{ __type__: 'PerspectiveCamera', fov: 50, aspect: wc.width / wc.height, near: 0.1, far: 100 }, { __type__: 'OrbitControls', target: { x: 0, y: 1, z: 0 } }] }, { __type__: 'Object3D', name: 'sphere', components: [{ __type__: 'MeshRenderer', geometry: { __type__: 'SphereGeometry', radius: 2, segmentsW: 64, segmentsH: 32 }, material: { __type__: 'StandardMaterial', uniforms: { u_diffuse: { __type__: 'Color4', r: 1, g: 1, b: 1, a: 1 }, u_specular: { __type__: 'Color4', r: 0.8, g: 0.8, b: 0.8, a: 1 }, u_glossiness: 80, u_reflectivity: 0 } } }] }, { __type__: 'Object3D', name: 'floor', position: { x: 0, y: -2.5, z: 0 }, rotation: { x: -1.5708, y: 0, z: 0 }, components: [{ __type__: 'MeshRenderer', geometry: { __type__: 'PlaneGeometry', width: 25, height: 25 }, material: { __type__: 'StandardMaterial', uniforms: { u_diffuse: { __type__: 'Color4', r: 0.4, g: 0.4, b: 0.4, a: 1 }, u_specular: { __type__: 'Color4', r: 0.2, g: 0.2, b: 0.2, a: 1 }, u_glossiness: 30, u_reflectivity: 0 } } }] }, ...lights] } };
const vl = logic(v);
ticker.onframe(() => { const t = Date.now() * 0.001; for (let i = 0; i < 6; i++) { const a = t * 0.5 + i * 1.047; reactive(lights[i]).position = { x: Math.cos(a) * 8, y: Math.sin(t + i) * 2 + 1, z: Math.sin(a) * 8 }; } webgpu.submit(vl.submit); });
