import { WebGPU } from '@feng3d/webgpu';
import { createTextureFromCanvas, logic, Object3D, reactive, Scene, TextureMaterial, View, ticker } from 'feng3d';
const wc = document.getElementById('webgpu') as HTMLCanvasElement;
const webgpu = await new WebGPU().init();
const tc = document.createElement('canvas'); tc.width = tc.height = 256; const tx = tc.getContext('2d')!;
const tex = createTextureFromCanvas(tc);
let cr:{x:number;y:number;z:number};
const v: View = { __type__: 'View', canvas: wc, root: { __type__: 'Object3D', name: 'U', components: [{ __type__: 'Scene', background: { __type__: 'Color4', r: 0.1, g: 0.1, b: 0.1, a: 1 }, ambientColor: { __type__: 'Color4', r: 1, g: 1, b: 1, a: 1 } }], children: [{ __type__: 'Object3D', name: 'cam', position: { x: 0, y: 0, z: 5 }, rotation: cr={x:0,y:0,z:0}, components: [{ __type__: 'PerspectiveCamera', fov: 50, aspect: wc.width/wc.height, near: 0.1, far: 100 }, { __type__: 'OrbitControls', target: { x: 0, y: 0, z: 0 } }] }, { __type__: 'Object3D', name: 'cube', rotation: { x: 0, y: 0, z: 0 }, components: [{ __type__: 'MeshRenderer', geometry: { __type__: 'CubeGeometry', width: 2.5, height: 2.5, depth: 2.5 }, material: { __type__: 'TextureMaterial', uniforms: { u_color: { __type__: 'Color4', r: 1, g: 1, b: 1, a: 1 } }, s_texture: tex as unknown as TextureMaterial['s_texture'] } }] }] } };
const vl = logic(v);
ticker.onframe(() => { const t = Date.now()*0.002; tx.fillStyle = '#000'; tx.fillRect(0,0,256,256); for (let i=0; i<8; i++) { const a=t+i*0.8; tx.beginPath(); tx.arc(128+Math.cos(a)*60, 128+Math.sin(a*1.3)*60, 20+Math.sin(t+i)*10, 0, 6.28); tx.fillStyle = 'hsl('+((t*50+i*45)%360)+',80%,60%)'; tx.fill(); } (reactive(tex) as { writeTextures: unknown[] }).writeTextures = [{ image: tc }]; reactive(cr).y += 0.005; webgpu.submit(vl.submit); });
