import { WebGPU } from '@feng3d/webgpu';
import { logic, Object3D, reactive, Scene, StandardMaterial, View, ticker } from 'feng3d';
const wc = document.getElementById('webgpu') as HTMLCanvasElement;
const webgpu = await new WebGPU().init();
const boxes: Object3D[] = [];
for (let i = 0; i < 50; i++) boxes.push({ __type__: 'Object3D', name: `b${i}`, position: { x: (Math.random()-0.5)*60, y: (Math.random()-0.5)*30, z: -Math.random()*100-5 }, rotation: { x: Math.random()*3, y: Math.random()*3, z: 0 }, components: [{ __type__: 'MeshRenderer', geometry: { __type__: 'CubeGeometry', width: 3, height: 3, depth: 3 }, material: { __type__: 'StandardMaterial', uniforms: { u_diffuse: { __type__: 'Color4', r: Math.random()*0.5+0.3, g: Math.random()*0.5+0.3, b: Math.random()*0.5+0.3, a: 1 }, u_specular: { __type__: 'Color4', r: 0, g: 0, b: 0, a: 1 }, u_glossiness: 0, u_reflectivity: 0 } } }] });
let gr:{x:number;y:number;z:number};
const v: View = { __type__: 'View', canvas: wc, root: { __type__: 'Object3D', name: 'U', components: [{ __type__: 'Scene', background: { __type__: 'Color4', r: 0.15, g: 0.2, b: 0.25, a: 1 }, ambientColor: { __type__: 'Color4', r: 0.6, g: 0.65, b: 0.7, a: 1 } }], children: [{ __type__: 'Object3D', name: 'cam', position: { x: 0, y: 0, z: 10 }, rotation: gr={x:0,y:0,z:0}, components: [{ __type__: 'PerspectiveCamera', fov: 60, aspect: wc.width/wc.height, near: 0.1, far: 200 }, { __type__: 'OrbitControls', target: { x: 0, y: 0, z: -30 } }] }, { __type__: 'Object3D', name: 'l', position: { x: 0.5, y: 1, z: 0.5 }, components: [{ __type__: 'DirectionalLight', color: { __type__: 'Color3', r: 1, g: 1, b: 1 }, intensity: 1 }] }, ...boxes] } };
const vl = logic(v);
ticker.onframe(() => { reactive(gr).y += 0.001; webgpu.submit(vl.submit); });
